extends Node

enum Style {F_BODY,M_BODY,F_HAIR,M_HAIR,F_SHIRT,M_SHIRT,F_PANTS,M_PANTS,F_SHOES,M_SHOES}
enum Tool {SWING,AXE,HOE,SEED,WATER,FISH}
enum Machine {SPRINKLER, FISHER, SCARECROW, DELETE}
enum State {DEFAULT, FISHING, BUILDING, SHOP}
#enum Seed {TOMATO, CORN, PUMPKIN, WHEAT}
enum Seed {STRAWBERRY,CARROT,BLUEBERRY}
enum Item {STRAWBERRY,CARROT,BLUEBERRY,WOOD,APPLE,CORN,WHEAT,PUMPKIN,TOMATO, FISH}
